import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Components
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Providers wrap around our application and give them accesss to data.
// NextThemesProvider = Give our Application access to light / dark mode data.
// Provider are generally on the client side "use client"
// Switch from light mode to dark mode  <-- user interaction / need the client To exist

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
